//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualBasic;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
using System;
namespace JCsTools.Xml.Formatter.Tests.My.Resources
{

  //This Class was auto-generated by the StronglyTypedResourceBuilder
  //Class via a tool like ResGen or Visual Studio.
  //To add or remove a member, edit your .ResX file then rerun ResGen
  //with the /str option, or rebuild your VS project.
  ///<summary>
  ///  A strongly-typed resource class, for looking up localized strings, etc.
  ///</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
  internal class Resources
  {

    private global::System.Resources.ResourceManager resourceMan;

    private global::System.Globalization.CultureInfo resourceCulture;

    ///<summary>
    ///  Returns the cached ResourceManager instance used by this class.
    ///</summary>
    [System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JCsTools.Xml.Formatter.Tests.Resources", typeof(Resources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    ///<summary>
    ///  Overrides the current thread's CurrentUICulture property for all
    ///  resource lookups using this strongly typed resource class.
    ///</summary>
    [System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal global::System.Globalization.CultureInfo Culture {
      get { return resourceCulture; }
      set { resourceCulture = value; }
    }

    ///<summary>
    ///  Looks up a localized string similar to &lt;root __rootId=&quot;1&quot;&gt;&lt;object __id=&quot;1&quot; __type=&quot;JCsTools.Xml.Formatter.Tests.Person, JCsTools.Xml.Formatter.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&quot; FirstName=&quot;Jan-Cornelius Molnar&quot; Age=&quot;12362486&quot; Address=&quot;2&quot; Girlfriends=&quot;3&quot; Data=&quot;4&quot; /&gt;&lt;object __id=&quot;2&quot; __type=&quot;JCsTools.Xml.Formatter.Tests.Address, JCsTools.Xml.Formatter.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&quot; StreetName=&quot;C:\Windows\system32&quot; City=&quot;JAN-NB&quot; /&gt;&lt;list __id=&quot;3&quot; __type=&quot;System.Collections.Generic.List`1[[Syst [rest of string was truncated]&quot;;.
    ///</summary>
    internal string DummyDataDocument {
      get { return ResourceManager.GetString("DummyDataDocument", resourceCulture); }
    }
  }
}

