//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualBasic;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
using System;
namespace JCsTools.Core.Interfaces.My.Resources
{

  //This Class was auto-generated by the StronglyTypedResourceBuilder
  //Class via a tool like ResGen or Visual Studio.
  //To add or remove a member, edit your .ResX file then rerun ResGen
  //with the /str option, or rebuild your VS project.
  ///<summary>
  ///  A strongly-typed resource class, for looking up localized strings, etc.
  ///</summary>
  [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Strings
  {
    private static global::System.Resources.ResourceManager resourceMan;

    private static global::System.Globalization.CultureInfo resourceCulture;

    [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings() : base()
    {
    }

    ///<summary>
    ///  Returns the cached ResourceManager instance used by this class.
    ///</summary>
    [System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    static internal global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JCsTools.Core.Interfaces.Strings", typeof(Strings).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    ///<summary>
    ///  Overrides the current thread's CurrentUICulture property for all
    ///  resource lookups using this strongly typed resource class.
    ///</summary>
    [System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    static internal global::System.Globalization.CultureInfo Culture {
      get { return resourceCulture; }
      set { resourceCulture = value; }
    }

    ///<summary>
    ///  Looks up a localized string similar to Could not find any implementation of the supplied interface..
    ///</summary>
    static internal string ImplementationNotFound_Generic {
      get { return ResourceManager.GetString("ImplementationNotFound_Generic", resourceCulture); }
    }

    ///<summary>
    ///  Looks up a localized string similar to Could not find any implementation of interface &quot;{0}&quot;..
    ///</summary>
    static internal string ImplementationNotFound_WithTypeName {
      get { return ResourceManager.GetString("ImplementationNotFound_WithTypeName", resourceCulture); }
    }

    ///<summary>
    ///  Looks up a localized string similar to Could not find any service implementation of the supplied service contract..
    ///</summary>
    static internal string ServiceImplementationNotFoundMessage_Generic {
      get { return ResourceManager.GetString("ServiceImplementationNotFoundMessage_Generic", resourceCulture); }
    }

    ///<summary>
    ///  Looks up a localized string similar to Could not find any service implementation of interface &quot;{0}&quot;..
    ///</summary>
    static internal string ServiceImplementationNotFoundMessage_WithTypeName {
      get { return ResourceManager.GetString("ServiceImplementationNotFoundMessage_WithTypeName", resourceCulture); }
    }
  }
}

