//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.VisualBasic;
using System;
using System.Collections;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Windows.Forms;
namespace JCsTools.JCQ.Ux
{
  [System.Runtime.CompilerServices.CompilerGeneratedAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
  internal sealed partial class WindowSettings : global::System.Configuration.ApplicationSettingsBase
  {
    private static WindowSettings defaultInstance = (WindowSettings)global::System.Configuration.ApplicationSettingsBase.Synchronized(new WindowSettings());

    public static WindowSettings Default {
      get { return defaultInstance; }
    }

    [System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("400")]
    public double MainWindowWidth {
      get { return (double)this("MainWindowWidth"); }
      set { this("MainWindowWidth") = value; }
    }

    [System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("600")]
    public double MainWindowHeight {
      get { return (double)this("MainWindowHeight"); }
      set { this("MainWindowHeight") = value; }
    }

    [System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("20")]
    public double MainWindowTop {
      get { return (double)this("MainWindowTop"); }
      set { this("MainWindowTop") = value; }
    }

    [System.Configuration.UserScopedSettingAttribute(), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Configuration.DefaultSettingValueAttribute("20")]
    public double MainWindowLeft {
      get { return (double)this("MainWindowLeft"); }
      set { this("MainWindowLeft") = value; }
    }
  }
}

